#!/usr/bin/env ruby
#
# OVERVIEW
# --------
#
#   This script decodes an SD-JWT.
#
# USAGE
# -----
#
#   decode-sd-jwt ${SD_JWT}
#


require "base64"
require "digest/sha2"
require "json"


def prettify_json(input)
  JSON.pretty_generate(JSON.parse(input))
end

def sha256(input)
  Digest::SHA256.digest(input)
end

def decode_base64url(input)
  Base64.urlsafe_decode64(input)
end

def encode_base64url(input)
  Base64.urlsafe_encode64(input, padding: false)
end

def decode_disclosure(input)
  digest  = encode_base64url(sha256(input))
  decoded = decode_base64url(input)

  prettify_json "{ \"#{digest}\": #{decoded} }"
end

def decode_jwt(input)
  fields = input.split('.')

  header  = prettify_json(decode_base64url(fields[0]))
  payload = prettify_json(decode_base64url(fields[1]))

  "#{header}\n#{payload}"
end

def decode_sd_jwt(input)
  output = ""

  input.split('~').each do |field|
    if field.include?('.')
      output << decode_jwt(field)
    else
      output << decode_disclosure(field)
    end

    output << "\n"
  end

  output
end

puts decode_sd_jwt(ARGV[0])
